---
- name: Create a new user for the Node.js app
  hosts: web
  become: yes
  tasks:
    - name: Create user "nodeapp"
      user:
        name: nodeapp
        shell: /bin/bash
        create_home: yes

