---
- name: Deploy Node.js App
  hosts: web
  become: yes
  tasks:
    - name: Copy app to server
      copy:
        src: ../files/app.tar.gz
        dest: /home/nodeapp/app.tar.gz
        owner: nodeapp
        group: nodeapp

    - name: Extract app
      unarchive:
        src: /home/nodeapp/app.tar.gz
        dest: /home/nodeapp/
        remote_src: yes
        owner: nodeapp
        group: nodeapp

    - name: Install dependencies
      npm:
        path: /home/nodeapp/app
        state: present

    - name: Start app (example)
      shell: node /home/nodeapp/app/index.js &

